name: Trigger auto deployment for acae

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/acae-AutoDeployTrigger-bd9af589-711d-43a5-b440-ac7c28ac9543.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ACAE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ACAE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ACAE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: evolvable.azurecr.io
          registryUsername: ${{ secrets.ACAE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACAE_REGISTRY_PASSWORD }}
          containerAppName: acae
          resourceGroup: DefaultResourceGroup-CUS
          imageToBuild: evolvable.azurecr.io/acae:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


